[template]
name        = "Rust"
description = "A language empowering everyone to build reliable and efficient software."
icon        = "ewogICJ0aW1lc3RhbXAiIDogMTczNTQxMjk4MTA4NCwKICAicHJvZmlsZUlkIiA6ICJhYzY1NDYwOWVkZjM0ODhmOTM0ZWNhMDRmNjlkNGIwMCIsCiAgInByb2ZpbGVOYW1lIiA6ICJzcGFjZUd1cmxTa3kiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjFiZjlkZmYxMTU4MzBlYzZlOGFlOTE0YTJiMjBmOTE0YzkyYjZjMjYyZjYyYTRhMDJmMWQ2YjkyNjBmYjUwOCIsCiAgICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9CiAgfQp9"
homepage    = "https://www.rust-lang.org"

exclude = [
    "target",
    "Cargo.lock",
    "rustc-ice-*.txt",
    "icon.png"
]
